#
# (c) Copyright 2024-2024, Agence du Numérique en Santé (ANS) (https://esante.gouv.fr). All rights reserved.
#

name: Docker image CI

on:
  push:
    branches: [ $default-branch  ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker buildx . --tag fr.gouv.ans.psc.example.esante.proxy:${GITHUB_SHA}
